// Generated by CoffeeScript 1.3.3
var Adapter, adapter,
  __hasProp = {}.hasOwnProperty,
  __slice = [].slice;

Adapter = (function() {

  function Adapter() {}

  Adapter.prototype.name = "Native";

  Adapter.prototype.domReady = function(callback) {
    return callback();
  };

  Adapter.prototype.create = function(htmlString) {
    var div;
    div = document.createElement("div");
    div.innerHTML = htmlString;
    return div.childNodes;
  };

  Adapter.prototype.wrap = function(element) {
    if (!(element instanceof Array || element instanceof NodeList)) {
      element = [element];
    }
    return element;
  };

  Adapter.prototype.$ = function() {
    return this.wrap.apply(this, arguments);
  };

  Adapter.prototype.unwrap = function(element) {
    return this.$(element)[0];
  };

  Adapter.prototype.tagName = function(element) {
    return this.$(element)[0].tagName;
  };

  Adapter.prototype.attr = function(element, attr, value) {
    var _base;
    if (value != null) {
      return this.$(element)[0].setAttribute(attr, value);
    } else {
      return typeof (_base = this.$(element)[0]).getAttribute === "function" ? _base.getAttribute(attr) : void 0;
    }
  };

  Adapter.prototype.find = function(element, selector) {
    return this.$(element)[0].querySelector(selector);
  };

  Adapter.prototype.findAll = function(element, selector) {
    return this.$(element)[0].querySelectorAll(selector);
  };

  Adapter.prototype.addClass = function(element, className) {
    return this.$(element)[0].classList.add(className);
  };

  Adapter.prototype.update = function(element, content, escape) {
    element = this.$(element)[0];
    if (escape) {
      while (element.firstChild) {
        element.removeChild(element.firstchild);
      }
      return element.appendChild(document.createTextNode(content));
    } else {
      return element.innerHTML = content;
    }
  };

  Adapter.prototype.removeClass = function(element, className) {
    return this.$(element)[0].classList.remove(className);
  };

  Adapter.prototype.css = function(element, properties) {
    var key, value, _results;
    element = this.$(element);
    _results = [];
    for (key in properties) {
      if (!__hasProp.call(properties, key)) continue;
      value = properties[key];
      _results.push(element.style[key] = value);
    }
    return _results;
  };

  Adapter.prototype.observe = function(element, eventName, observer) {
    return this.$(element)[0].addEventListener(eventName, observer);
  };

  Adapter.prototype.stopObserving = function(element, eventName, observer) {
    return this.$(element)[0].removeEventListener(eventName, observer);
  };

  Adapter.prototype.clone = function(object) {
    var key, newObject, val;
    newObject = {};
    for (key in object) {
      if (!__hasProp.call(object, key)) continue;
      val = object[key];
      newObject[key] = val;
    }
    return newObject;
  };

  Adapter.prototype.extend = function() {
    var key, source, sources, target, val, _i, _len;
    target = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      source = sources[_i];
      for (key in source) {
        if (!__hasProp.call(source, key)) continue;
        val = source[key];
        target[key] = val;
      }
    }
    return target;
  };

  return Adapter;

})();

adapter = new Adapter;

Opentip.adapters["native"] = adapter;

Opentip.adapter = adapter;
