// Generated by CoffeeScript 1.3.3
var $, Adapter, adapter,
  __hasProp = {}.hasOwnProperty;

$ = ender;

$.ender({
  opentip: function(content, title, options) {
    return new Opentip(this, content, title, options);
  }
}, true);

Adapter = (function() {

  function Adapter() {}

  Adapter.prototype.domReady = function(callback) {
    return $.domReady(callback);
  };

  Adapter.prototype.create = function(html) {
    return $(html);
  };

  Adapter.prototype.wrap = function(element) {
    element = $(element);
    if (element.length > 1) {
      throw new Error("Multiple elements provided.");
    }
    return element;
  };

  Adapter.prototype.clone = function(object) {
    var key, newObject, val;
    newObject = {};
    for (key in object) {
      if (!__hasProp.call(object, key)) continue;
      val = object[key];
      newObject[key] = val;
    }
    return newObject;
  };

  return Adapter;

})();

adapter = new Adapter;

Opentip.adapters.ender = adapter;

Opentip.adapter = adapter;
