// Generated by CoffeeScript 1.3.3
var $, Adapter, adapter;

$ = ender;

Adapter = (function() {

  function Adapter() {}

  Adapter.prototype.domReady = $.domReady.apply($, arguments);

  Adapter.prototype.create = function(html) {
    return $(html);
  };

  return Adapter;

}).apply(this, arguments);

adapter = new Adapter;

Opentip.adapters.ender = adapter;

Opentip.adapter = adapter;
