// Generated by CoffeeScript 1.3.3
/*
More info at http://www.opentip.org

Copyright (c) 2012, Matias Meno
Graphics by Tjandra Mayerhold

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

/*
Usage:

<div data-ot="This will be viewed in tooltip"></div>

or externally:

$('elementId').addTip('Content', { options });

For a full documentation, please visit http://www.opentip.org/
*/

var Opentip;

Opentip = {
  version: "2.0.0-dev",
  STICKS_OUT_TOP: 1,
  STICKS_OUT_BOTTOM: 2,
  STICKS_OUT_LEFT: 1,
  STICKS_OUT_RIGHT: 2,
  cached: {},
  debugging: false,
  debug: function() {
    if (this.debugging && ((typeof console !== "undefined" && console !== null ? console.debug : void 0) != null)) {
      return console.debug.apply(console, arguments);
    }
  },
  objectIsEvent: function(obj) {
    return typeof obj === "object" && obj.type && obj.screenX;
  },
  lastTipId: 1,
  lastZIndex: 100,
  documentIsLoaded: false,
  postponeCreation: function(createFunction) {
    if (!(Opentip.documentIsLoaded || !Opentip.IEVersion())) {
      return Event.observe(window, "load", createFunction);
    }
  },
  adapters: {},
  adapter: null,
  position: {
    top: 0,
    topRight: 1,
    right: 2,
    bottomRight: 3,
    bottom: 4,
    bottomLeft: 5,
    left: 6,
    topLeft: 7
  },
  sanitizePosition: function(arrayPosition) {
    var position, positionString;
    if (arrayPosition instanceof Array) {
      positionString = "";
      if (arrayPosition[0] === "center") {
        positionString = arrayPosition[1];
      } else if (arrayPosition[1] === "middle") {
        positionString = arrayPosition[0];
      } else {
        positionString = arrayPosition[1] + this.ucfirst(arrayPosition[0]);
      }
    } else if (typeof arrayPosition === "string") {
      positionString = arrayPosition;
    }
    position = this.position[positionString];
    if (position == null) {
      throw "Unknown position: " + positionString;
    }
    return position;
  },
  vendors: "Khtml Ms O Moz Webkit".split(" "),
  testDiv: document.createElement("div"),
  supports: function(prop) {
    if (prop in Opentip.testDiv.style) {
      return true;
    }
    prop = this.ucfirst(prop);
    return Opentip.vendors.any(function(vendor) {
      return vendor + prop in Opentip.testDiv.style;
    });
  }
};

Opentip.ucfirst = function(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
};
