// Generated by CoffeeScript 1.3.3
var $,
  __hasProp = {}.hasOwnProperty;

$ = ender;

describe("Opentip - Startup", function() {
  var adapter, opentip;
  adapter = Opentip.adapters["native"];
  opentip = null;
  beforeEach(function() {
    return Opentip.adapter = adapter;
  });
  afterEach(function() {
    var prop, _ref;
    for (prop in opentip) {
      if (!__hasProp.call(opentip, prop)) continue;
      if ((_ref = opentip[prop]) != null) {
        if (typeof _ref.restore === "function") {
          _ref.restore();
        }
      }
    }
    if (opentip != null) {
      if (typeof opentip.deactivate === "function") {
        opentip.deactivate();
      }
    }
    $("[data-ot]").remove();
    return $(".opentip-container").remove();
  });
  return it("should find all elements with data-ot()", function() {
    $("<div data-ot=\"Content text\"></div>");
    return Opentip.findElements();
  });
});
