// Generated by CoffeeScript 1.3.3

describe("utils", function() {
  describe("sanitizePosition()", function() {
    it("should properly camelize positions", function() {
      expect(Opentip.prototype.sanitizePosition("top-left")).to.equal("topLeft");
      expect(Opentip.prototype.sanitizePosition("top-Right")).to.equal("topRight");
      return expect(Opentip.prototype.sanitizePosition("BOTTOM left")).to.equal("bottomLeft");
    });
    return it("should handle any order of positions", function() {
      expect(Opentip.prototype.sanitizePosition("right bottom")).to.equal("bottomRight");
      expect(Opentip.prototype.sanitizePosition("left left middle")).to.equal("left");
      return expect(Opentip.prototype.sanitizePosition("left - top")).to.equal("topLeft");
    });
  });
  return describe("ucfirst()", function() {
    return it("should transform the first character to uppercase", function() {
      return expect(Opentip.prototype.ucfirst("abc def")).to.equal("Abc def");
    });
  });
});
